from . import product_product
from . import res_partner_design
from . import res_partner
from . import orderline_design_upload
from . import sale_order_line
from . import order_imprint_design
from . import website
from . import res_config_settings
from . import product_template
from . import product_template_attribute_value
from . import product_printing_method
from . import product_design_template
from . import editor_text_template
from . import editor_canvas_preset
from . import editor_canvas_product_option
from . import product_design_share
from . import orderline_vdp_record
from . import sale_order

